name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Configurar variables de entorno a partir de secrets
      - name: Set Environment Variables from Secrets
        env:
          OKTA_ISSUER_URI: ${{ secrets.OKTA_ISSUER_URI }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
        run: echo "Environment variables loaded"

      - name: Install Dependencies
        run: npm ci

      - name: Run server
        env:
          OKTA_ISSUER_URI: ${{ secrets.OKTA_ISSUER_URI }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
        run: npm start
