name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # Ver el ciclo de lanzamientos de Node.js: https://nodejs.org/en/about/releases/

    steps:
      # Checkout del repositorio
      - uses: actions/checkout@v4

      # Configurar la versión de Node.js usando la matriz
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Instalar dependencias
      - name: Install Dependencies
        run: npm ci

      # Ejecutar el servidor de desarrollo si es necesario (opcional)
      - name: Start Development Server
        if: ${{ always() }}  # Opcional, remover si no es necesario levantar el server
        run: npm run dev &

      # Ejecutar tests con Mocha
      - name: Run Tests
        run: npm test

      # Publicar logs y artefactos si los tests fallan (opcional)
      - name: Upload Test Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: ./logs/
